In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
automobiles_data = pd.read_csv('datasets/CarPrice_Assignment.csv')

automobiles_data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [3]:
automobiles_data.shape

(205, 26)

In [4]:
automobiles_data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [7]:
automobiles_data.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [8]:
automobiles_data = pd.get_dummies(automobiles_data)

In [11]:
automobiles_data.head()

,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,...,cylindernumber_twelve,cylindernumber_two,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,...,0,0,0,0,0,0,0,1,0,0
1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,...,0,0,0,0,0,0,0,1,0,0
2,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,...,0,0,0,0,0,0,0,1,0,0
3,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,...,0,0,0,0,0,0,0,1,0,0
4,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,...,0,0,0,0,0,0,0,1,0,0

In [12]:
automobiles_data.shape

(205, 52)

In [13]:
X = automobiles_data.drop('price', axis=1)

Y = automobiles_data['price']

In [14]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [17]:
model = LinearRegression()

model.fit(x_train, y_train)

LinearRegression()

In [23]:
training_score = model.score(x_train, y_train)

training_score

0.9475080436082186

In [19]:
y_pred = model.predict(x_test)

In [21]:
testing_score = r2_score(y_test, y_pred)

testing_score

0.8777537658302089

In [24]:
import json

In [25]:
model.coef_

array([-1.24922013e+01, -7.05911871e+01,  9.08956366e+02,  1.92379815e+02,
        3.50029252e+00,  1.26698175e+02, -2.16631916e+03, -4.08276734e+03,
       -3.50233340e+02, -1.02501976e+01,  2.06425713e+00, -1.85885877e+02,
        2.09251664e+02,  1.80192550e+03, -1.80192550e+03, -1.24273154e+03,
        1.24273154e+03,  1.21526237e+02, -1.21526237e+02,  2.23205402e+03,
       -1.46729262e+02, -9.48507896e+02,  1.88929432e+02, -1.32574629e+03,
       -4.91436100e+02, -4.48391263e+02,  9.39827363e+02, -4.42939880e+03,
        4.42939880e+03,  1.01955349e+03, -3.96058330e+03, -8.99096157e+02,
        3.11713077e+03,  1.50157730e+03, -4.21084993e+03,  3.43226782e+03,
        4.46848857e+03, -2.64457924e+03, -4.04377745e+03, -1.64663446e+03,
        5.57261469e+03, -5.13837992e+03,  3.43226782e+03,  1.03335395e+03,
        7.18416263e+02, -1.85961466e+03,  1.80192550e+03, -1.30265229e+03,
        8.65989333e+02, -1.25741810e+03,  0.00000000e+00])

In [26]:
model.intercept_

-48552.838763142965

In [27]:
model_params = {}

model_params['coef'] = list(model.coef_)
model_params['intercept'] = model.intercept_.tolist()

In [28]:
json_txt = json.dumps(model_params, indent=4)

json_txt

'{\n    "coef": [\n        -12.49220131921816,\n        -70.59118710852054,\n        908.9563664160087,\n        192.37981473582553,\n        3.5002925232623263,\n        126.69817462858495,\n        -2166.3191636087267,\n        -4082.7673403516296,\n        -350.2333402688259,\n        -10.250197644265807,\n        2.064257130122573,\n        -185.88587726005613,\n        209.2516644589688,\n        1801.9254966892813,\n        -1801.9254966892784,\n        -1242.7315384768233,\n        1242.731538476804,\n        121.5262372995907,\n        -121.52623729960334,\n        2232.0540156426237,\n        -146.72926199951746,\n        -948.507895667263,\n        188.92943198419187,\n        -1325.7462899601167,\n        -491.4360997524407,\n        -448.39126325843404,\n        939.827363010826,\n        -4429.398795489186,\n        4429.398795489191,\n        1019.5534928991163,\n        -3960.583301395967,\n        -899.096157467914,\n        3117.1307729903065,\n        1501.577300342141,\n        -4210.849925552918,\n        3432.2678181851265,\n        4468.4885660941445,\n        -2644.579241252527,\n        -4043.7774483551016,\n        -1646.6344645516363,\n        5572.614694316313,\n        -5138.379924436288,\n        3432.2678181851284,\n        1033.3539533182623,\n        718.4162631345561,\n        -1859.6146609597408,\n        1801.925496689263,\n        -1302.652288949909,\n        865.9893326080181,\n        -1257.4180958404722,\n        0.0\n    ],\n    "intercept": -48552.838763142965\n}'

In [29]:
with open('models/regressor_param.txt', 'w') as file:
    file.write(json_txt)

In [30]:
with open('models/regressor_param.txt', 'r') as file:
    json_text = json.load(file)

In [31]:
json_model = LinearRegression()

In [32]:
json_model.coef_ = np.array(json_text['coef'])
json_model.intercept_ = np.array(json_text['intercept'])

In [33]:
y_pred = json_model.predict(x_test)

r2_score(y_test, y_pred)

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

0.8777537658302089

In [34]:
import pickle

In [36]:
pickle.dump(model, open('models/model.pkl', 'wb'))

In [37]:
pickle_model = pickle.load(open('models/model.pkl', 'rb'))

In [38]:
y_pred = pickle_model.predict(x_test)

r2_score(y_test, y_pred)

0.8777537658302089

In [39]:
import joblib

In [40]:
joblib.dump(model, 'models/model.joblib')

['models/model.joblib']

In [41]:
joblib_model = joblib.load('models/model.joblib')

In [42]:
y_pred = joblib_model.predict(x_test)

r2_score(y_test, y_pred)

0.8777537658302089